src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view, SignUpView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('signup/', SignUpView.as_view(), name='signup')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, records, ProfileView, delete_recipe, UpdateRecipeView, about, update_success

app_name = 'recipes'
urlpatterns = [
   path('', home),
   path('recipes/', RecipeListView.as_view(), name='recipes-list'),
   path('recipes/<pk>/', RecipeDetailView.as_view(), name='recipes-detail'),
   path('search/', records, name='records-search'),
   path('profile/', ProfileView.as_view(), name='user-profile'),
   path('profile/<pk>/delete/', delete_recipe, name='delete-recipe'),
   path('profile/<pk>/update/', UpdateRecipeView.as_view(), name='update-recipe'),
   path('about/', about, name='about'),
   path('update_success/', update_success, name='update-success')
]

src/recipes/models.py
from django.db import models
from django.shortcuts import reverse


difficulty_choices =[('Easy', 'Easy'), ('Medium', 'Medium'), ('Intermediate', 'Intermediate'), ('Hard', 'Hard')]

# Create your models here.
class Recipe(models.Model):
    name = models.CharField(max_length=50)
    cook_time = models.PositiveIntegerField(help_text="In minutes")
    instructions = models.TextField()
    description = models.TextField()
    difficulty = models.CharField(max_length=20, choices = difficulty_choices, default='Easy')
    pic = models.ImageField(upload_to='recipe_pics', default='default.jpg')
    created_by = models.ForeignKey('auth.User', on_delete=models.CASCADE, related_name='recipes', default=1)

    def __str__(self):
        return f"Name: {self.name}, Description: {self.description}, Cook Time (min): {self.cook_time}, Difficulty: {self.difficulty}"

    def get_absolute_url(self):
       return reverse ('recipes:recipes-detail', kwargs={'pk': self.pk})
    
    def get_delete_url(self):
        return reverse('recipes:delete-recipe', kwargs={'pk': self.pk})
    
    def get_update_url(self):
        return reverse('recipes:update-recipe', kwargs={'pk': self.pk})
    
    def calculate_difficulty(self):
        from recipe_ingredients.models import RecipeIngredient
        MAX_EASY_TIME = 10
        MAX_EASY_INGREDIENTS = 4

        ingredients = RecipeIngredient.objects.filter(recipe=self)

        self.difficulty = "Hard"
        if(self.cook_time < MAX_EASY_TIME and len(ingredients) < MAX_EASY_INGREDIENTS):
            self.difficulty = "Easy"
        elif(self.cook_time < MAX_EASY_TIME):
            self.difficulty = "Medium"
        elif(len(ingredients) < MAX_EASY_INGREDIENTS):
            self.difficulty = "Intermediate"

   


    

src/recipes/forms.py
from django import forms
from .models import Recipe

difficulty_choices = [
    ('Any', 'Any'),
    ('Easy', 'Easy'),
    ('Medium', 'Medium'),
    ('Intermediate', 'Intermediate'),
    ('Hard', 'Hard')
]

class RecipesSearchForm(forms.Form):
    recipe = forms.CharField(label='Recipe', max_length=100, required=False)
    ingredient = forms.CharField(label='Ingredient', max_length=100, required=False)
    difficulty = forms.ChoiceField(label='Difficulty', choices=difficulty_choices, required=False)


  
class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'description', 'cook_time', 'instructions', 'ingredients', 'pic']
    name = forms.CharField(label='Name', max_length=50)
    description = forms.CharField(label='Description', widget=forms.Textarea(attrs={'class': 'fixed-text-field'}))
    cook_time = forms.IntegerField(label='Cook Time (min)')
    ingredients = forms.CharField(label='Ingredients', widget=forms.Textarea(attrs={'class': 'fixed-text-field'}))
    instructions = forms.CharField(label='Instructions', widget=forms.Textarea(attrs={'class': 'fixed-text-field'}))
    pic = forms.ImageField(label='Picture', required=False, widget=forms.FileInput)


    def clean_cook_time(self):
        data = self.cleaned_data['cook_time']
        if data is not None and data < 0:
            raise forms.ValidationError("Enter a positive number")
        return data

src/recipes/views.py
# Django imports
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, TemplateView, UpdateView
from django.contrib.auth.decorators import login_required
from django.db.models.functions import Lower
from django.contrib.auth.mixins import LoginRequiredMixin

# App imports
from .models import Recipe
from recipe_ingredients.models import RecipeIngredient
from ingredients.models import Ingredient
from .forms import RecipesSearchForm
from .forms import RecipeForm
from .utils import get_chart

# Third-party imports
import pandas as pd


# Create your views here.
# home: Renders the home page for the recipes app
def home(request):
    return render(request, 'recipes/recipes_home.html')

# RecipeListView: Renders a list of all recipes
class RecipeListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'recipes/recipes_list.html'
    context_object_name = 'recipes'
    ordering = ['name']

# RecipeDetailView: Renders the details of a single recipe
class RecipeDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = 'recipes/recipes_detail.html'
    context_object_name = 'recipe'
    
    # get_context_data: Overrides the get_context_data method to add the ingredients to the context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipe = self.object
        recipe.calculate_difficulty()
        recipe.save()
        
        # Retrieve ingredients for the current recipe
        ingredients = RecipeIngredient.objects.filter(recipe=self.object).order_by('ingredient__name')
        
        # Add ingredients to the context
        context['recipe_ingredients'] = ingredients
        
        return context
    
# records: Renders the records page for the recipes app
@login_required 
def records(request):
    form = RecipesSearchForm(request.POST or None)
    qs = None
    recipes_df = pd.DataFrame(Recipe.objects.all().order_by('name').values())
    chart = None

    if request.method == 'POST':
        form = RecipesSearchForm(request.POST)
        if form.is_valid():
            recipe = request.POST.get('recipe')
            ingredient = request.POST.get('ingredient')
            difficulty = request.POST.get('difficulty')
            
            # Filter recipes based on the recipe name
            if recipe:
                qs = Recipe.objects.filter(name__icontains=recipe)

            # Filter recipes based on the ingredient name
            if ingredient:
                ingredient = ingredient.lower()
                ingredient_query = RecipeIngredient.objects.filter(ingredient__name__icontains=ingredient).annotate(lower_name=Lower('ingredient__name')).values('recipe').distinct()
                if qs:
                    qs = qs.filter(id__in=ingredient_query)
                else:
                    qs = Recipe.objects.filter(id__in=ingredient_query)

            # Filter recipes based on the difficulty level
            if form.cleaned_data.get('difficulty') != 'Any':
                if qs:
                    qs = qs.filter(difficulty=difficulty)
                else:
                    qs = Recipe.objects.filter(difficulty=difficulty)
            elif qs is None:
                qs = Recipe.objects.all().values()
                    

            # Create a dataframe with the filtered recipes
            if qs:
                qs = qs.order_by('name')
                recipes_df = pd.DataFrame(qs.values())
            else:
                recipes_df = pd.DataFrame()

     
    if recipes_df.empty is False:
        difficulty = recipes_df['difficulty'].value_counts()
        chart=get_chart(difficulty, labels=recipes_df['difficulty'].unique())   
               
    context = {'form': form, 'recipes_df': recipes_df, 'chart': chart}      
    return render(request, 'recipes/records.html', context)

# ProfileView: Renders the user profile page for the recipes app       
class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'recipes/profile.html'
    
   
    # get_context_data: Overrides the get_context_data method to add the current user to the context
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        context['form'] = RecipeForm()
        context['recipes'] = Recipe.objects.filter(created_by=self.request.user).order_by('name')
        return context
    
    def post(self, request, *args, **kwargs):
        
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            print('valid')
            recipe = Recipe.objects.create(name=form.cleaned_data['name'], description=form.cleaned_data['description'], cook_time=form.cleaned_data['cook_time'], created_by=self.request.user, instructions=form.cleaned_data['instructions'])

            if form.cleaned_data['pic']:
                recipe.pic = form.cleaned_data['pic']
                recipe.save()
            
            recipe.calculate_difficulty()
            recipe.save()

            ingredients_input = form.cleaned_data['ingredients']
            ingredients_names = [name.strip() for name in ingredients_input.splitlines()]

            for name in ingredients_names:
                ingredient = Ingredient.objects.filter(name=name).first()
                if ingredient is None:
                    ingredient = Ingredient.objects.create(name=name)
                RecipeIngredient.objects.create(recipe=recipe, ingredient=ingredient)

            return redirect(request.path)
        else:
            context = self.get_context_data(form=form)
            context['form_errors'] = form.errors
            print(form.errors)
            return self.render_to_response(context)
        
# delete_recipe: Deletes a recipe
@login_required
def delete_recipe(request, pk):
    try:
        recipe = Recipe.objects.get(pk=pk)
    except Recipe.DoesNotExist:
        return HttpResponse(status=404)
    
    recipe.delete()
    return redirect('recipes:user-profile')

# UpdateRecipeView: Renders the update recipe page for the recipes app
class UpdateRecipeView(LoginRequiredMixin, UpdateView):
    template_name = 'recipes/update_recipe.html'
    form_class = RecipeForm
    queryset = Recipe.objects.all()
    success_url = '/update_success/'
    
    # get_initial: Overrides the get_initial method to add the ingredients to the initial form data
    def get_initial(self):
        initial = super().get_initial()
        recipe = self.get_object()
        # Get the list of ingredients associated with the recipe
        recipe_ingredients = RecipeIngredient.objects.filter(recipe=recipe)
        # Format the list of ingredients into a string
        ingredient_list = '\n'.join([recipe_ingredient.ingredient.name for recipe_ingredient in recipe_ingredients])
        # Set the formatted string as the initial value for the textarea
        initial['ingredients'] = ingredient_list
        return initial
    
    # form_valid: Overrides the form_valid method to update the recipe and ingredients
    def form_valid(self, form):
        form.instance.user = self.request.user

        # Get the current recipe instance
        recipe = self.get_object()

        # Save the recipe form to update recipe details
        recipe_form = form.save(commit=False)
        recipe_form.save()

        # Update ingredients
        ingredients_input = form.cleaned_data['ingredients']
        ingredients_names = [name.strip() for name in ingredients_input.splitlines()]
        
        RecipeIngredient.objects.filter(recipe=recipe).delete()

        # Create new ingredients
        for name in ingredients_names:
            ingredient = Ingredient.objects.filter(name=name).first()
            if ingredient is None:
                ingredient = Ingredient.objects.create(name=name)
            RecipeIngredient.objects.create(recipe=recipe, ingredient=ingredient)

        
        return super().form_valid(form)

    # form_invalid: Overrides the form_invalid method to handle invalid form submissions
    def form_invalid(self, form):
        
        self.object = self.get_object()
        context = self.get_context_data(form=form)
        context['form_errors'] = form.errors
        return self.render_to_response(context)
  
# about: Renders the about page for the recipes app
@login_required
def about(request):
    return render(request, 'recipes/about.html')

# update_success: Renders the update success page for the recipes app
@login_required
def update_success(request):
    return render(request, 'recipes/update_success.html')

src/recipes/templates/recipes/about.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>About</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'recipes/css/about.css' %}" />
  </head>
  <body>
    {% include 'recipes/navbar.html' %}

    <div class="content-container">
      <h1>About</h1>
      <h2>Dominic DeCicco</h2>
      <h3>e-mail</h3>
      <p>ddecicco330@gmail.com</p>
      <h3>Portfolio</h3>
      <a href="https://dominicdecicco.io/">dominicdecicco.io</a>
      <h3>GitHub</h3>
      <a href="https://github.com/ddecicco330web/">github.com/ddeicco330web</a>
    </div>
  </body>
</html>

src/recipes/templates/recipes/navbar.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Recipes</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div class="navbar">
      <a class="link" href="{% url 'recipes:records-search' %}">
        All Recipes
      </a>
      <a class="link" href="{% url 'recipes:user-profile' %}"> Profile </a>
      <a class="link" href="{%url 'recipes:about' %}"> About </a>
      <a class="link" href="{%url 'logout' %}"> Logout </a>
    </div>
  </body>
</html>

src/recipes/templates/recipes/profile.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Profile</title>
    <link rel="stylesheet" href="{% static 'recipes/css/profile.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <script src="{% static 'recipes/js/modal.js' %}"></script>
  </head>
  <body>
    <div class="content-container">
      <!--Navbar-->
      {% include 'recipes/navbar.html' %}

      <h1>{{ user.username }}</h1>

      <!--User Recipes-->
      <h2>Your Recipes</h2>
      <div class="card-container">
        <div class="add-card card" onclick="handleOpen()">
          <img
            class="card-img add-card-img"
            src="{% static 'recipes/img/add.png' %}"
            alt="add"
          />
        </div>
        {% for recipe in recipes %}
        <div class="card">
          <img
            class="card-img"
            src="{{ recipe.pic.url }}"
            alt="{{ recipe.name }}"
          />
          <a href="{{ recipe.get_absolute_url }}">{{ recipe.name }}</a>
          <div class="card-buttons">
            <a href="{{recipe.get_update_url}}">
              <button class="update-button">
                <img
                  src="{% static 'recipes/img/edit.png' %}"
                  alt="edit"
                  class="edit-img"
                />
              </button>
            </a>
            <a href="{{recipe.get_delete_url}}">
              <button class="delete-button">X</button>
            </a>
          </div>
        </div>

        {% endfor %}
      </div>

      <!--Add Recipe Modal-->
      {% if form_errors %}
      <script>
        document.addEventListener('DOMContentLoaded', function () {
          console.log('open modal');
          handleOpen();
        });
      </script>
      {% endif %}
      <div class="add-recipe-modal">
        <form method="post" enctype="multipart/form-data">
          <button class="close-button" type="button" onclick="{handleClose()}">
            X
          </button>
          {{form_errors}} {% csrf_token %}
          <div class="form-group-container">
            <!--Left Column-->
            <div class="left-column">
              <div class="form-group">
                <label>Name:</label>
                {{ form.name }}
              </div>
              <div class="form-group">
                <label>Cook Time (min):</label>
                {{ form.cook_time }}
              </div>
              <div class="form-group">
                <label>Picture:</label>
                {{ form.pic }}
              </div>
              <div class="form-group">
                <label>Description:</label>
                {{ form.description }}
              </div>
            </div>

            <!--Right Column-->
            <div class="right-column">
              <div class="form-group">
                <label>Ingredients:</label>
                {{ form.ingredients }}
              </div>
              <div class="form-group">
                <label>Instructions:</label>
                {{ form.instructions }}
              </div>
            </div>
          </div>
          <button class="add-button" type="submit">Add</button>
        </form>
      </div>
    </div>
  </body>
</html>

src/recipes/templates/recipes/recipes_detail.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>{{ recipe.name }}</title>
    <link rel="stylesheet" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="{% static 'recipes/css/recipes_detail.css' %}"
    />
  </head>
  <body>
    <div class="content-container">
      {% include 'recipes/navbar.html' %}
      <div class="recipe-container">
        <div class="back-link-container">
          <a href="{{ request.META.HTTP_REFERER }}">Back</a>
        </div>
        <h1>{{recipe.name}}</h1>
        <div class="main-info">
          <img
            class="recipe-img"
            src="{{ recipe.pic.url }}"
            alt="{{ recipe.name }}"
          />
          <div class="main-info-text">
            <p>{{recipe.description}}</p>
            <div class="inline-row">
              <h2>Cooking Time:</h2>
              <p>{{ recipe.cook_time }} mins</p>
            </div>
            <div class="inline-row">
              <h2>Difficulty:</h2>
              <p>{{recipe.difficulty}}</p>
            </div>
          </div>
        </div>
        <div class="ingredients">
          <h2>Ingredients</h2>
          <ul>
            {% for recipe_ingredient in recipe_ingredients %}
            <li>{{recipe_ingredient.ingredient.name}}</li>
            {% endfor %}
          </ul>
        </div>

        <div class="instructions">
          <h2>Instructions</h2>
          <p>{{recipe.instructions|linebreaks}}</p>
        </div>
      </div>
    </div>
  </body>
</html>

src/recipes/templates/recipes/recipes_home.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Recipes</title>
    <link rel="stylesheet" href="{% static 'recipes/css/home.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div class="content-container">
      <img src="{% static '/img/welcome.jpg' %}" alt="Recipes" />
      <div class="text-container">
        <h1 class="welcome-text">Welcome to Recipes</h1>
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'signup' %}">Signup</a>
      </div>
    </div>
  </body>
</html>

src/recipes/templates/recipes/recipes_list.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <title>Recipes</title>
    <link rel="stylesheet" href="{% static 'recipes/css/recipes_list.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div class="content-container">
      <!--Navbar-->
      {% include 'recipes/navbar.html' %}

      <!--Card container-->
      <div class="card-container">
        {% for recipe in recipes %}
        <div class="card">
          <img
            class="card-img"
            src="{{recipe.pic.url}}"
            alt="{{recipe.name}}"
          />
          <a href="{{recipe.get_absolute_url}}">{{recipe.name}}</a>
        </div>

        {% endfor %}
      </div>
    </div>
  </body>
</html>

src/recipes/templates/recipes/records.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Search</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="{% static 'recipes/css/search.css' %}" />
  </head>
  <body>
    <div class="content-container">
      <!-- Navbar -->
      {% include 'recipes/navbar.html' %}

      <!-- Search form -->
      <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group-container">
          <div class="form-group">
            <label for="id_recipe">Recipe:</label>
            {{ form.recipe }}
          </div>
          <div class="form-group">
            <label for="id_ingredient">Ingredient:</label>
            {{ form.ingredient }}
          </div>
          <div class="form-group">
            <label for="id_difficulty">Difficulty:</label>
            {{ form.difficulty }}
          </div>
        </div>
        <button type="submit">Search</button>
      </form>

      <div class="results-container">
        <!-- Recipe cards -->
        <div class="card-container">
          {% for index, row in recipes_df.iterrows %}
          <div class="card">
            <img
              class="card-img"
              src="{{ MEDIA_URL }}{{ row.pic }}"
              alt="{{ row.name }}"
            />
            <a href="{% url 'recipes:recipes-detail' pk=row.id %}"
              >{{ row.name }}</a
            >
          </div>
          {% endfor %}
        </div>

        {% if chart %}
        <!-- Charts -->
        <div class="chart-container">
          <img
            src="data:image/png;base64, {{ chart|safe }}"
            alt="pie chart"
            width="100%"
          />
        </div>
        {% endif %}
      </div>
    </div>

    <script src="{% static 'recipes/js/tabs.js'%}"></script>
  </body>
</html>

src/recipes/templates/recipes/update_recipe.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Update Recipe</title>
    <link
      rel="stylesheet"
      href="{% static 'recipes/css/update_recipe.css' %}"
    />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div class="content-container">
      {% include 'recipes/navbar.html' %}

      <h1>Update Recipe</h1>
      <form method="post" enctype="multipart/form-data">
        {{form_errors}} {% csrf_token %}
        <div class="form-group-container">
          <!--Left Column-->
          <div class="left-column">
            <div class="form-group">
              <label>Name:</label>
              {{ form.name }}
            </div>
            <div class="form-group">
              <label>Cook Time (min):</label>
              {{ form.cook_time }}
            </div>

            <div class="form-group">
              <label>Description:</label>
              {{ form.description }}
            </div>

            <div class="form-group">
              <label>Picture:</label>
              <p>Current</p>
              {{recipe.pic.url}}

              <p>Change</p>
              {{ form.pic }}
            </div>
          </div>

          <!--Right Column-->
          <div class="right-column">
            <div class="form-group">
              <label>Ingredients:</label>
              {{ form.ingredients }}
            </div>
            <div class="form-group">
              <label>Instructions:</label>
              {{ form.instructions }}
            </div>
          </div>
        </div>
        <button class="update-button" type="submit">Update</button>
      </form>
    </div>
  </body>
</html>

src/recipes/templates/recipes/update_success.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Success</title>
    <link rel="stylesheet" href="{% static '/css/success.css' %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div class="content-container">
      <img src="{% static '/img/welcome.jpg' %}" alt="Recipes" />
      <h1>Success</h1>
      <p>You have successfully updated the recipe.</p>
      <a href="{% url 'recipes:user-profile' %}">OK</a>
    </div>
  </body>
</html>